- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: copy nginx Reverse proxy conf file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Run tasks/app-pre-req.yaml instead of 'main'
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: Starting Nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true

- name: Newrelic Setup Nginx
  ansible.builtin.import_role:
    name: Newrelic
    tasks_from: nginx

