- name: Download and Install Prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    owner: bin

- name: Copy service file
  ansible.builtin.template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start node_exporter Server
  ansible.builtin.systemd_service:
    name: node_exporter
    state: restarted
    enabled: true
    daemon_reload: true