- name: Clean Old content
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent

- name: Creating Directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory

- name: Download and Extract App content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
    dest: "{{ app_loc }}"
    remote_src: yes
